default:
  navigation:
   - title: "NUESTRA TRADICIÓN"
     subtitle: ""
     url: "#"
   - title: "NUESTRO FRUTO"
     subtitle: ""
     url: "#"
   - title: "PROCESO"
     subtitle: ""
     url: "#"
   - title: "ENCUENTRA TU FRUTO"
     subtitle: ""
     url: "#"
   - title: "CONTACTO"
     subtitle: ""
     url: "#"
    