default:
  navigation:
   - title: "NUESTRA TRADICIÓN"
     subtitle: ""
     url: "https://www.frutodelsol.com.mx/#"
   - title: "NUESTRO FRUTO"
     subtitle: ""
     url: "https://www.frutodelsol.com.mx/nuestro-fruto.html"
   - title: "PROCESO"
     subtitle: ""
     url: "https://www.frutodelsol.com.mx/proceso.html"
   - title: "ENCUENTRA TU FRUTO"
     subtitle: ""
     url: "https://www.frutodelsol.com.mx/encuentra-tu-fruto.html"
   - title: "CONTACTO"
     subtitle: ""
     url: "https://www.frutodelsol.com.mx/contacto.html"
    